image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
   - apt-get update -qq && apt-get install
   - npm install

stages:
  - install
  - build
  - test

script:
  - npm run build