version: 0.2 

phases:
  install:
    runtime-versions:  
      nodejs: 10
    commands:
      - echo npm installing
      - npm install

  build:
    commands:
      - echo npm run build
      - npm run build
      # - echo npm run test
      # - npm run test

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - /public
